<?php

use Illuminate\Database\Seeder;

class SgimatrizincidentesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sgimatrizincidentes')->delete();
        
        \DB::table('sgimatrizincidentes')->insert(array (
            0 => 
            array (
                'id' => 1,
            'name' => 'Spam (Correo basura)',
                'descripcion' => 'Ataques dirigidos a dañar la imagen de la empresa o utilizar medios electrónicos para otros usos ilícitos.',
                'categoria' => 'Contenido Abusivo',
                'c' => 0,
                'i' => 1,
                'd' => 1,
                'solucion' => 'Uso adecuado del Maleware',
                'seccion_id' => 8,
                'grupo_id' => 1,
                'responsablen1' => 1,
                'responsablen2' => 3,
                'evidencia' => 0,
                'created_at' => '2020-06-30 09:45:32',
                'updated_at' => '2020-07-01 08:40:36',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Falla o sobrecarga de los sistemas de información',
                'descripcion' => 'Interrupción de la operación a causa de problemas eléctricos, de redes o de sobrexplotación de los medios.',
                'categoria' => 'Falla en las operaciones',
                'c' => 0,
                'i' => 0,
                'd' => 1,
                'solucion' => NULL,
                'seccion_id' => 4,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-06 10:45:44',
                'updated_at' => '2020-08-06 10:45:44',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Falla o sobrecarga de las comunicaciones',
                'descripcion' => 'Interrupción de la operación a causa de problemas eléctricos, de redes o de sobrexplotación de los medios.',
                'categoria' => 'Falla en las operaciones',
                'c' => 0,
                'i' => 1,
                'd' => 1,
                'solucion' => NULL,
                'seccion_id' => 4,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-06 10:48:36',
                'updated_at' => '2020-08-06 10:48:36',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Racismo/Pederastia',
                'descripcion' => 'Ataques dirigidos a dañar la imagen de la
organización o a utilizar sus medios electrónicos
para otros usos ilícitos (tales como la publicidad, la
extorsión o, en general la ciberdelincuencia).',
                'categoria' => 'Contenido abusivo',
                'c' => 0,
                'i' => 1,
                'd' => 0,
                'solucion' => NULL,
                'seccion_id' => 8,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-07 16:41:29',
                'updated_at' => '2020-08-07 16:41:29',
            ),
            4 => 
            array (
                'id' => 5,
            'name' => 'Delitos (Acoso/extorsión/ mensajes ofensivos)',
                'descripcion' => 'Ataques dirigidos a dañar la imagen de la
organización o a utilizar sus medios electrónicos
para otros usos ilícitos (tales como la publicidad, la
extorsión o, en general la ciberdelincuencia).',
                'categoria' => 'Contenido abusivo',
                'c' => 1,
                'i' => 1,
                'd' => 0,
                'solucion' => NULL,
                'seccion_id' => NULL,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-07 17:12:30',
                'updated_at' => '2020-08-07 17:12:30',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Uso ilegitimo de credenciales',
                'descripcion' => 'Incidentes relacionados con acciones fraudulentas derivadas de suplantación de identidad, en todas sus variantes.',
                'categoria' => 'Fraude',
                'c' => 1,
                'i' => 1,
                'd' => 0,
                'solucion' => NULL,
                'seccion_id' => 8,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-07 17:13:28',
                'updated_at' => '2020-08-07 17:13:28',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Violaciones de derechos de propiedad intelectual o industrial.',
                'descripcion' => 'Incidentes relacionados con acciones fraudulentas derivadas de suplantación de identidad, en todas sus variantes.',
                'categoria' => 'Fraude',
                'c' => 0,
                'i' => 1,
                'd' => 0,
                'solucion' => NULL,
                'seccion_id' => 8,
                'grupo_id' => NULL,
                'responsablen1' => NULL,
                'responsablen2' => NULL,
                'evidencia' => 0,
                'created_at' => '2020-08-07 17:14:11',
                'updated_at' => '2020-08-07 17:14:11',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'suplantación/spoofing (dirección IP falseada simula la identidad de otra máquina de la red para conseguir acceso a recursos de
un tercer sistema',
                    'descripcion' => 'Incidentes relacionados con acciones fraudulentas derivadas de suplantación de identidad, en todas sus variantes.',
                    'categoria' => 'Fraude',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:15:46',
                    'updated_at' => '2020-08-07 17:15:46',
                ),
                8 => 
                array (
                    'id' => 9,
                    'name' => 'exfiltración de información',
                    'descripcion' => 'Incidentes relacionados con acciones fraudulentas derivadas de suplantación de identidad, en todas sus variantes.',
                    'categoria' => 'Fraude',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:16:38',
                    'updated_at' => '2020-08-07 17:16:38',
                ),
                9 => 
                array (
                    'id' => 10,
                    'name' => 'Sistema desactualizado',
                    'descripcion' => 'Incidentes relacionados por violaciones de usuarios
de las políticas de seguridad aprobadas por la
organización.',
                    'categoria' => 'Políticas de seguridad de la información',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:17:33',
                    'updated_at' => '2020-08-07 17:17:33',
                ),
                10 => 
                array (
                    'id' => 11,
                'name' => 'Incumplimiento en alguna politica de seguridad (Contraseñas, desarrollo seguro,  uso de activos de información, proveedores, dispositivos móviles, control de accesos, pantalla limpia y escritorio limpio, tratamiento de datos, entre otros…)',
                    'descripcion' => 'Incidentes relacionados por violaciones de usuarios
de las políticas de seguridad aprobadas por la
organización.',
                    'categoria' => 'Políticas de seguridad de la información',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:18:29',
                    'updated_at' => '2020-08-07 17:18:29',
                ),
                11 => 
                array (
                    'id' => 12,
                    'name' => 'Uso indebido de la marca',
                    'descripcion' => 'Incidentes relacionados por violaciones de usuarios
de las políticas de seguridad aprobadas por la
organización.',
                    'categoria' => 'Políticas de seguridad de la información',
                    'c' => 0,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:20:15',
                    'updated_at' => '2020-08-07 17:20:15',
                ),
                12 => 
                array (
                    'id' => 13,
                    'name' => 'Infracciones de derechos de autor o piratería',
                    'descripcion' => 'Incidentes relacionados por violaciones de usuarios
de las políticas de seguridad aprobadas por la
organización.',
                    'categoria' => 'Políticas de seguridad de la información',
                    'c' => 0,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:21:16',
                    'updated_at' => '2020-08-07 17:21:16',
                ),
                13 => 
                array (
                    'id' => 14,
                    'name' => 'Abuso de privilegios por usuario  y usos inadecuados',
                    'descripcion' => 'Incidentes relacionados por violaciones de usuarios
de las políticas de seguridad aprobadas por la
organización.',
                    'categoria' => 'Políticas de seguridad de la información',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 4,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:22:20',
                    'updated_at' => '2020-08-07 17:22:20',
                ),
                14 => 
                array (
                    'id' => 15,
                    'name' => 'Cambios en componentes de infraestructura tecnológica sin respetar los niveles de autorización preestablecidos',
                    'descripcion' => NULL,
                    'categoria' => 'Cambios operacionales y en aplicaciones',
                    'c' => 0,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 6,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:23:19',
                    'updated_at' => '2020-08-07 17:23:19',
                ),
                15 => 
                array (
                    'id' => 16,
                    'name' => 'Cambios no controlados en sistemas de Información',
                    'descripcion' => NULL,
                    'categoria' => 'Cambios operacionales y en aplicaciones',
                    'c' => 0,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:23:58',
                    'updated_at' => '2020-08-07 17:23:58',
                ),
                16 => 
                array (
                    'id' => 17,
                    'name' => 'Modificación, instalación o eliminación no autorizada de software',
                    'descripcion' => NULL,
                    'categoria' => 'Cambios operacionales y en aplicaciones',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:25:13',
                    'updated_at' => '2020-08-07 17:25:13',
                ),
                17 => 
                array (
                    'id' => 18,
                    'name' => 'Contraseñas debiles',
                    'descripcion' => NULL,
                    'categoria' => 'Cambios operacionales y en aplicaciones',
                    'c' => 0,
                    'i' => 0,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 4,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:25:55',
                    'updated_at' => '2020-08-07 17:25:55',
                ),
                18 => 
                array (
                    'id' => 19,
                    'name' => 'Modificación no autorizada de un sitio o página web de la empresa',
                    'descripcion' => NULL,
                    'categoria' => 'Cambios operacionales y en aplicaciones',
                    'c' => 0,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:26:36',
                    'updated_at' => '2020-08-07 17:26:36',
                ),
                19 => 
                array (
                    'id' => 20,
                    'name' => 'Incidentes de terrorismo',
                    'descripcion' => NULL,
                    'categoria' => 'Daños físicos',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:27:40',
                    'updated_at' => '2020-08-07 17:27:40',
                ),
                20 => 
                array (
                    'id' => 21,
                'name' => 'Desastres no naturales(Incendios, derrumbes por mala construcción, otros)',
                    'descripcion' => NULL,
                    'categoria' => 'Daños físicos',
                    'c' => 0,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:28:10',
                    'updated_at' => '2020-08-07 17:28:10',
                ),
                21 => 
                array (
                    'id' => 22,
                'name' => 'Desastres naturales(sismos, inundaciones, otros)',
                    'descripcion' => NULL,
                    'categoria' => 'Daños físicos',
                    'c' => 0,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:28:51',
                    'updated_at' => '2020-08-07 17:28:51',
                ),
                22 => 
                array (
                    'id' => 23,
                    'name' => 'Daños o cambios físicos no autorizados a los sistemas',
                    'descripcion' => NULL,
                    'categoria' => 'Daños físicos',
                    'c' => 0,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 4,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:29:32',
                    'updated_at' => '2020-08-07 17:29:32',
                ),
                23 => 
                array (
                    'id' => 24,
                    'name' => 'Alarmas de sistemas de monitorización',
                    'descripcion' => NULL,
                    'categoria' => 'Pruebas y reconocimientos',
                    'c' => 0,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:30:42',
                    'updated_at' => '2020-08-07 17:30:42',
                ),
                24 => 
                array (
                    'id' => 25,
                    'name' => 'Pruebas no autorizadas',
                    'descripcion' => NULL,
                    'categoria' => 'Pruebas y reconocimientos',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:31:23',
                    'updated_at' => '2020-08-07 17:31:23',
                ),
                25 => 
                array (
                    'id' => 26,
                    'name' => 'Uso no autorizado de la informacion en formato digital o fisico',
                'descripcion' => 'Incidentes relacionados al control de la información documentada y de los sistemas (digital o fisica) que podran ocasionar daños de disponiblidad, reprocesos o ambiguedades en la información',
                    'categoria' => 'Custodia de Información',
                    'c' => 0,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 6,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:32:14',
                    'updated_at' => '2020-08-07 17:32:14',
                ),
                26 => 
                array (
                    'id' => 27,
                    'name' => 'Destrucción no autorizada de información',
                'descripcion' => 'Incidentes relacionados al control de la información documentada y de los sistemas (digital o fisica) que podrán ocasionar daños de disponibilidad, reprocesos o ambigüedades en la información',
                    'categoria' => 'Custodia de Información',
                    'c' => 0,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:33:14',
                    'updated_at' => '2020-08-07 17:33:14',
                ),
                27 => 
                array (
                    'id' => 28,
                    'name' => 'Robo de información fisica',
                'descripcion' => 'Incidentes relacionados al control de la información documentada y de los sistemas (digital o fisica) que podran ocasionar daños de disponiblidad, reprocesos o ambiguedades en la información',
                    'categoria' => 'Custodia de Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 5,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:34:08',
                    'updated_at' => '2020-08-07 17:34:08',
                ),
                28 => 
                array (
                    'id' => 29,
                    'name' => 'Robo de información digital',
                'descripcion' => 'Incidentes relacionados al control de la información documentada y de los sistemas (digital o fisica) que podran ocasionar daños de disponiblidad, reprocesos o ambiguedades en la información',
                    'categoria' => 'Custodia de Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:34:40',
                    'updated_at' => '2020-08-07 17:34:40',
                ),
                29 => 
                array (
                    'id' => 30,
                'name' => 'Pérdida de información (en forma fisica o digital) en servicios, equipos o instalaciones.',
                'descripcion' => 'Incidentes relacionados al control de la información documentada y de los sistemas (digital o fisica) que podran ocasionar daños de disponiblidad, reprocesos o ambiguedades en la información',
                    'categoria' => 'Custodia de Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 5,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:35:19',
                    'updated_at' => '2020-08-07 17:35:19',
                ),
                30 => 
                array (
                    'id' => 31,
                    'name' => 'Uso inadecuado de la Información contenida en recursos tecnológicos de la empresa o en medios fisicos.',
                    'descripcion' => 'Incidentes relacionados con el acceso y fuga
(Confidencialidad), modificación o borrado
(Integridad) de información no pública.',
                    'categoria' => 'Acceso y uso de la Información',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 7,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:37:43',
                    'updated_at' => '2020-08-07 17:37:43',
                ),
                31 => 
                array (
                    'id' => 32,
                    'name' => 'Acceso Logicos no autorizados respecto al correo electronico, internet, fileserver, otros servicios tecnologicos,redes.',
                    'descripcion' => 'Incidentes relacionados con el acceso y fuga
(Confidencialidad), modificación o borrado
(Integridad) de información no pública.',
                    'categoria' => 'Acceso y uso de la Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 4,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:38:31',
                    'updated_at' => '2020-08-07 17:38:31',
                ),
                32 => 
                array (
                    'id' => 33,
                    'name' => 'Divulgación no autorizada de información digital',
                    'descripcion' => 'Incidentes relacionados con el acceso y fuga
(Confidencialidad), modificación o borrado
(Integridad) de información no pública.',
                    'categoria' => 'Acceso y uso de la Información',
                    'c' => 1,
                    'i' => 1,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 4,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:39:27',
                    'updated_at' => '2020-08-07 17:39:27',
                ),
                33 => 
                array (
                    'id' => 34,
                    'name' => 'Divulgación no autorizada de información física',
                    'descripcion' => 'Incidentes relacionados con el acceso y fuga
(Confidencialidad), modificación o borrado
(Integridad) de información no pública.',
                    'categoria' => 'Acceso y uso de la Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:40:01',
                    'updated_at' => '2020-08-07 17:40:01',
                ),
                34 => 
                array (
                    'id' => 35,
                    'name' => 'Acceso fisico No autorizado  a los recursos y/o Intalaciones de la empresa sin la autorizacon debida.',
                    'descripcion' => 'Incidentes relacionados con el acceso y fuga
(Confidencialidad), modificación o borrado
(Integridad) de información no pública.',
                    'categoria' => 'Acceso y uso de la Información',
                    'c' => 1,
                    'i' => 0,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 5,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:40:37',
                    'updated_at' => '2020-08-07 17:40:37',
                ),
                35 => 
                array (
                    'id' => 36,
                    'name' => 'No Bloqueo de la pantalla, información en el puesto de trabajo expuesta, escritorio bastante lleno',
                    'descripcion' => NULL,
                    'categoria' => 'Humano',
                    'c' => 1,
                    'i' => 0,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:41:12',
                    'updated_at' => '2020-08-07 17:41:12',
                ),
                36 => 
                array (
                    'id' => 37,
                    'name' => 'Envio de email a personas equivocadas',
                    'descripcion' => NULL,
                    'categoria' => 'Humano',
                    'c' => 1,
                    'i' => 0,
                    'd' => 0,
                    'solucion' => NULL,
                    'seccion_id' => 3,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:41:39',
                    'updated_at' => '2020-08-07 17:41:39',
                ),
                37 => 
                array (
                    'id' => 38,
                'name' => 'Ataques de denegación de servicio (DoS) o bloqueo de acceso',
                    'descripcion' => 'Software cuyo objetivo es infiltrarse o dañar un
ordenador, servidor u otro dispositivo de red, sin el
conocimiento de su responsable o usuario y con
finalidades muy diversas.',
                'categoria' => 'Hacking (Código dañino/malicioso)',
                    'c' => 1,
                    'i' => 0,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:44:08',
                    'updated_at' => '2020-08-07 17:44:08',
                ),
                38 => 
                array (
                    'id' => 39,
                'name' => 'Ataque o infección por código malicioso, spyware, Rootkit, Ransomware, Herramientas para acceso remoto (RAT), otros)',
                    'descripcion' => 'Ataques dirigidos a poner fuera de servicio los
sistemas, al objeto de causar daños en la
productividad y/o la imagen de las instituciones
atacadas.',
                'categoria' => 'Hacking (Código dañino/malicioso)',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:46:15',
                    'updated_at' => '2020-08-07 17:46:15',
                ),
                39 => 
                array (
                    'id' => 40,
                'name' => 'Ataques de Ingenieria social (Phishing)',
                    'descripcion' => 'Software cuyo objetivo es infiltrarse o dañar un
ordenador, servidor u otro dispositivo de red, sin el
conocimiento de su responsable o usuario y con
finalidades muy diversas.',
                'categoria' => 'Hacking (Código dañino/malicioso)',
                    'c' => 1,
                    'i' => 1,
                    'd' => 1,
                    'solucion' => NULL,
                    'seccion_id' => 8,
                    'grupo_id' => NULL,
                    'responsablen1' => NULL,
                    'responsablen2' => NULL,
                    'evidencia' => 0,
                    'created_at' => '2020-08-07 17:47:03',
                    'updated_at' => '2020-08-07 17:47:03',
                ),
            ));
        
        
    }
}